spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/astrocorner  # provided by docker container
    username: root                                # provided by docker container
    password: root                                # provided by docker container
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            client-id: 533972550540-qa05dtbe83pb8o319mn8qj6ilaoul4kr.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

  mail:
    host: localhost
    username: uhello
    password: phello
    port: 4025

app:
  security:
    jwt:
      access:
        secret: SECRET_KEY_FOR_ACCESS_TOKEN
        expiration-ms: 900000 # 900000 # 15 min
      refresh:
        secret: SECRET_KEY_FOR_REFRESH_TOKEN
        expiration-ms: 300000000 # 1296000000 # 15 days
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - http://localhost:8080/test/authenticated
